AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mini CDP Serverless

Globals:
  Function:
    Timeout: 30
    Runtime: python3.14
    Environment:
      Variables:
        ENV: dev
        S3_BUCKET: !Ref EventsBucket
        PROFILES_TABLE: !Ref ProfilesTable

Resources:

  EventsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mini-cdp-events-${AWS::AccountId}"

  ProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: mini-cdp-profiles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  IngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mini-cdp-ingestion
      CodeUri: src/ingestion/
      Handler: lambda_function.lambda_handler
      Description: Lambda de ingestão de eventos da Mini CDP
      Policies:
        - S3WritePolicy:
            BucketName: !Ref EventsBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ProfilesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /events
            Method: post

  ProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mini-cdp-profile
      CodeUri: src/profile/
      Handler: lambda_function.lambda_handler
      Description: Lambda de consulta de perfil da Mini CDP
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProfilesTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /profile/{userId}
            Method: get

Outputs:
  ApiEndpoint:
    Description: URL da API de ingestão
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/events"
  ProfileEndpoint:
    Description: URL da API de consulta de perfil
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profile/{userId}"
  EventsBucket:
    Description: Nome do bucket S3
    Value: !Ref EventsBucket
  ProfilesTable:
    Description: Nome da tabela DynamoDB
    Value: !Ref ProfilesTable